name: Bash Command Line
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test build-Build and run dev container task
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          make install
          make lint
          make test
          make format
